"""winner_count

Revision ID: 6fc356ba27dc
Revises: 38e747b3bd0c
Create Date: 2023-03-18 18:17:01.207175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fc356ba27dc"
down_revision = "38e747b3bd0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("winner", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "winner")
    # ### end Alembic commands ###
