"""voted

Revision ID: 876853606e38
Revises: 6fc356ba27dc
Create Date: 2023-03-19 11:47:36.278060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "876853606e38"
down_revision = "6fc356ba27dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members_contests", sa.Column("voted", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members_contests", "voted")
    # ### end Alembic commands ###
